language: objective-c
before_install:
- brew install xctool

script:
- xctool -workspace Example/CSCurrencyParser.xcworkspace -scheme CSCurrencyParser-Example test -sdk iphonesimulator  ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick
